### ISSUE TITLE
uTP Out-of-Range Error

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#274]
If random seqNr is generated too close to MAX_UINT16, uTP throws RangeError when seqNr incrementing goes over MAX.

```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 65535. Received 65536
    at new NodeError (node:internal/errors:371:5)
    at checkInt (node:internal/buffer:72:11)
    at writeU_Int16BE (node:internal/buffer:832:3)
    at Buffer.writeUInt16BE (node:internal/buffer:840:10)
    at packetToBuffer (/home/scottypoi/Documents/github/ultralight/packages/portalnetwork/dist/wire/utp/Packets/Packet.js:21:12)
    at Packet.encodePacket (/home/scottypoi/Documents/github/ultralight/packages/portalnetwork/dist/wire/utp/Packets/Packet.js:55:24)
```

Need a guard against seqNr's that climb past MAX_UINT16

Possible Solutions:
    - Flat ceiling for randUint16()  (Like MAX - 1000)

**Comment by acolytec3** [comment]
Fixed by #331
