### ISSUE TITLE
Find root cause of unhandled `discv5` exceptions

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#464]
We've been seeing unhandled exceptions thrown by `discv5` with errors like
```sh
    at callback (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/service/service.ts:466:20)
    at SessionService.rpcFailure (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/service/service.ts:1000:6)
    at SessionService.emit (node:events:514:28)
    at SessionService.emit (node:domain:489:12)
    at SessionService.failSession (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/session/service.ts:844:14)
    at SessionService.failRequest (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/session/service.ts:827:10)
    at SessionService.handleRequestTimeout (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/session/service.ts:784:12)
    at TimeoutMap.onTimeout (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/session/service.ts:153:12)
    at Timeout.<anonymous> (file:///home/jim/development/ultralight/node_modules/@chainsafe/discv5/src/util/timeoutMap.ts:30:16)
    at listOnTimeout (node:internal/timers:569:17)
```

This is likely a bug in `discv5` but not 100% clear yet.

**Comment by acolytec3** [comment]
Have opened [this issue](https://github.com/ChainSafe/discv5/issues/265) on the `discv5` library and waiting a response before we can address this.

**Comment by acolytec3** [comment]
Going to close this as I believe has been addressed on discv5 side.
